### ISSUE TITLE
效果好像不是很理想

### ISSUE THREAD

**Issue by zhanglaplace** [MirrorYuChen/ncnn_example#1]
这个106点的landmark效果好像不是很好，我这边没有匹配的人脸检测算法，直接用标注的rect框提取。结果如下
![image](https://user-images.githubusercontent.com/12178974/56707869-43413380-674d-11e9-944c-31f609a95266.png)

原图如下:
![image_0003](https://user-images.githubusercontent.com/12178974/56707908-623fc580-674d-11e9-9955-65f18d37a274.png)

**Comment by ChenjingYu1993** [comment]
> 这个106点的landmark效果好像不是很好，我这边没有匹配的人脸检测算法，直接用标注的rect框提取。结果如下
> ![image](https://user-images.githubusercontent.com/12178974/56707869-43413380-674d-11e9-944c-31f609a95266.png)
> 
> 原图如下:
> ![image_0003](https://user-images.githubusercontent.com/12178974/56707908-623fc580-674d-11e9-9955-65f18d37a274.png)

过几天我加一个MTCNN的检测接口你再试试~

**Comment by zhanglaplace** [comment]
@1976277169 好的，多谢～ 。

**Comment by Tomhouxin** [comment]
我也想尝试一下，把左博的那个mtcnn加进来试试

**Comment by MirrorYuChen** [comment]
来来来，可以把左博所有的模型转一波，再出一个项目~

**Comment by Tomhouxin** [comment]
要跟着你学学，哈哈，我知识层面还太窄了

**Comment by MirrorYuChen** [comment]
> 要跟着你学学，哈哈，我知识层面还太窄了

跟左博学习吧，认认真真的啃ZQCNN~

**Comment by MirrorYuChen** [comment]
可以试一下重新上传的大模型，可能效果会好一点~

**Comment by taylorguo** [comment]
> 可以试一下重新上传的大模型，可能效果会好一点~

能否把输入图像尺寸变大一点？比如，224x224， 或416x416，  效果应该会好一点？

**Comment by MirrorYuChen** [comment]
> > 可以试一下重新上传的大模型，可能效果会好一点~
> 
> 能否把输入图像尺寸变大一点？比如，224x224， 或416x416， 效果应该会好一点？

网络输入是固定的，如果修改网络输入大小，需要修改模型结构，最后很可能不能实时~

**Comment by taylorguo** [comment]
![227f1a934eae8647e87ac09742fd041f](https://user-images.githubusercontent.com/16943564/60859351-d6fea800-a244-11e9-8de1-406095cdc976.png)
96x96的效果， 大佬，我这效果也太差了， 你测试的有这么差吗？

**Comment by MirrorYuChen** [comment]
可以将你的测试代码上传一下吗？我这边测试没这么渣，这个模型应该是比之前上传的模型要好的~

**Comment by taylorguo** [comment]
代码：
https://github.com/taylorguo/MTCNN_Landmark106

**Comment by MirrorYuChen** [comment]
ncnn::Mat in = ncnn::Mat::from_pixels_resize((const unsigned char*)indata, ncnn::Mat::PIXEL_BGR, width, height, 48, 48);
        LOGI(" ******** JNI 图像格式转换完成, Mat已读入, 大小已经更改为(96x96).");

这个是你最终的测试代码吗？
你需要将这里的48,48改成96,96~

**Comment by taylorguo** [comment]
用的96的
![667f7779706e734b7cdad4204c55f814](https://user-images.githubusercontent.com/16943564/60866667-88a8d380-a25b-11e9-9155-252da46e74ad.png)

**Comment by MirrorYuChen** [comment]
java代码看着有点晕，传入关键点检测的image需要是对应人脸区域，也就是说对人脸检测结果进行关键点定位，你这里关键点检测传入的是人脸检测结果吗？

**Comment by taylorguo** [comment]
是的，我用https://github.com/moli232777144/mtcnn_ncnn
把人脸方框提取出来， 然后把方框裁剪出来放到网络里面推断

**Comment by MirrorYuChen** [comment]
你将人脸检测框也画上去看看~

**Comment by taylorguo** [comment]
![63aea9727648d12fa8a6a759673c4a47](https://user-images.githubusercontent.com/16943564/60867794-361ce680-a25e-11e9-9058-47214801c957.png)

**Comment by MirrorYuChen** [comment]
48x48的模型测试过了吗？

**Comment by taylorguo** [comment]
测过了，上面发的第一个测试图是48X48的，下面这个是96x96的
难道是因为图像通道数有问题？
Android里面传进来的是4通道的

**Comment by taylorguo** [comment]
你的测试结果发一下看看呗？

**Comment by MirrorYuChen** [comment]
给我一张你的测试图片，我晚上测试一下给你结果~

**Comment by taylorguo** [comment]
![e9775c1a76039938cbe9fd252980b9d3](https://user-images.githubusercontent.com/16943564/60868790-4df56a00-a260-11e9-945d-6851a3d7a47d.jpg)

**Comment by taylorguo** [comment]
应该是from_pixels_resize()第二个参数出问题了，改成PIXEL_RGBA2BGR，稍微好一点，但还是有问题
![8e7f9208d06cf033fab55e713bbfcaf4](https://user-images.githubusercontent.com/16943564/60870953-69627400-a264-11e9-9866-aaaa62be1388.jpg)

你帮我看看怎么改？
我还是要仔细看看ncnn源代码

**Comment by MirrorYuChen** [comment]
那就是你代码有问题咯，你仔细对着改吧，我这边模型肯定是没问题的，都测试过的~

**Comment by MirrorYuChen** [comment]
这个参数应该是PIXEL_RGB2BGR

**Comment by MirrorYuChen** [comment]
你可以参考下我给的测试代码~

**Comment by taylorguo** [comment]
你的测试效果，你还是帮我测一下，发我一下，我看看我能优化到什么程度

**Comment by MirrorYuChen** [comment]
不好意思，不会java，这个我心有余而力不足~我最多在linux或者windows上测试一下~

**Comment by taylorguo** [comment]
是的，你在其他系统上测试的结果

**Comment by taylorguo** [comment]
图像的通道已经改成3通道了，还是有问题，检测出来的landmark分布和上面这张图一样

**Comment by taylorguo** [comment]
我也是有点晕了，难道非要导个opencv的包进去？？

**Comment by MirrorYuChen** [comment]
![image](https://user-images.githubusercontent.com/49817428/60899097-77cc8200-a29c-11e9-8ea9-2b26159d9798.png)
你自己代码写的有问题，好好检查一下吧~

**Comment by taylorguo** [comment]
模型出来的点坐标没问题，Java画点有问题.

**Comment by taylorguo** [comment]
推断的时候，能否改成接受灰度图？

**Comment by MirrorYuChen** [comment]
不接受，你重新提个issue吧，这个已经关闭了，我新加了retinaface做人脸检测，可以去测试一下~

**Comment by deep-practice** [comment]
retinaface你是转的哪个项目的

**Comment by MirrorYuChen** [comment]
有问题，你可以重新开一个issue，找半天才找到~retinaface转的是insightface的吧，忘记了，很久以前的事了~
