### ISSUE TITLE
mtcnn memory 

### ISSUE THREAD

**Issue by baiyuang** [MirrorYuChen/ncnn_example#10]
![image](https://user-images.githubusercontent.com/4686933/66886481-03774c80-f00a-11e9-94f1-21fdb5ceff3a.png)

**Comment by MirrorYuChen** [comment]
能贴一下具体错误吗？欢迎PR

**Comment by baiyuang** [comment]
问题找到了，是因为你的ncnn/include和我编译的ncnn库不是一个版本导致的。
另外，还有个问题请教下，ZQLandmarker使用cpu非常高，这个有什么解决方法吗？

**Comment by MirrorYuChen** [comment]
你可以设置下线程数，把线程数设小一点，然后把模式设置成light模式，应该就会好很多~

**Comment by baiyuang** [comment]
嗯，确实，我把seetaface2的detect加进来了，cpu:i7+640*480，landmark可以到100fps了，cpu的load也比较低了，方便的话加我qq聊哈，qq：85985065。

**Comment by MirrorYuChen** [comment]
欢迎PR，我过几天会把centerface加到项目中~

**Comment by MirrorYuChen** [comment]
人脸数据库啥的近期也准备动手做了，前段时间太忙了~
