### ISSUE TITLE
您好，方便提供下centerface的benchmark吗（在嵌入式端，树梅派之类的平台）？

### ISSUE THREAD

**Issue by zjd1988** [MirrorYuChen/ncnn_example#13]

**Comment by MirrorYuChen** [comment]
这个可以去centerface项目那边提，这里我就是用ncnn测试了一下centerface，他们那边后面好像也出了个example~测试板子为RK3399
这个是那个群里面群友反馈的结果：
![image](https://user-images.githubusercontent.com/49817428/67445876-178e0000-f641-11e9-9bbe-238d17c9d644.png)

**Comment by MirrorYuChen** [comment]
这个后面有时间我会优化一下代码效率，然后再出benchmark~

**Comment by MirrorYuChen** [comment]
现在还有两个功能都没时间去实现~

**Comment by zjd1988** [comment]
@MirrorYuChen  嗯嗯，好的。谢谢回复！
