### ISSUE TITLE
您好，请问mxnet转ncnn时，比如左博的关键点模型，mxnet模型输入是4维，有batchsize，ncnn模型输入是3维，无batchsize，是这样吗，请问模型转换的时候需要做什么处理吗，谢谢

### ISSUE THREAD

**Issue by yang-ruixin** [MirrorYuChen/ncnn_example#14]

**Comment by MirrorYuChen** [comment]
关于维度问题，你这边理解的没有错，转换问题请看项目下方的readme，里面有关于转模型方法的链接，其实就是转完模型，然后将param文件中没用的层删除掉就好了，最后就是觉得有用，给个star哈~

**Comment by yang-ruixin** [comment]
> 关于维度问题，你这边理解的没有错，转换问题请看项目下方的readme，里面有关于转模型方法的链接，其实就是转完模型，然后将param文件中没用的层删除掉就好了，最后就是觉得有用，给个star哈~

谢谢回复，之前已经点过星了。
您说的删除层是删除最后没用的几层，我明白。
我现在想知道的是最开始输入时，4维转3维怎么处理，谢谢。
还是您只删除最后几层，而开头没做任何处理？

**Comment by MirrorYuChen** [comment]
所谓的四维不就是加了一个batch_size，实际上一张图片就是三维啊，不需要任何转换~

**Comment by MirrorYuChen** [comment]
你一张张输入就完事了，不知道是不是我没理解你的意思~

**Comment by yang-ruixin** [comment]
> 你一张张输入就完事了，不知道是不是我没理解你的意思~

其实是这样，我的人脸姿态角模型，从mxnet转ncnn，就是输一张图，但是2个模型输出结果不一样。
所以我想参考一下您转左博的关键点模型。
我再找找哪出问题了。
再次感谢回复。

**Comment by MirrorYuChen** [comment]
嗯嗯，有什么问题欢迎讨论交流！
