### ISSUE TITLE
跟踪

### ISSUE THREAD

**Issue by sosopop** [MirrorYuChen/ncnn_example#15]
啥时候增加人脸跟踪和人脸识别数据库

**Comment by MirrorYuChen** [comment]
这段时间有很多别的事，没时间弄，跟踪和数据库这块可以去看一下seetaface2里面的，后面有时间了准备白嫖一波~然后现在项目里面的代码还有优化，后期会继续优化，敬请期待~

**Comment by sosopop** [comment]
看来没法嫖你了，我再换个人看看吧

**Comment by MirrorYuChen** [comment]
可以玩seetaface2，功能很全~

**Comment by sosopop** [comment]
ok，thx

**Comment by sosopop** [comment]
seetaface2没源码啊

**Comment by sosopop** [comment]
哦，看错了

**Comment by Danbinabo** [comment]
你好，有106个关键点得测试代码吗？

**Comment by MirrorYuChen** [comment]
里面有测试代码，想批量测试自己改一下就好了~

**Comment by MirrorYuChen** [comment]
今天抽空从seetaface2把数据库和人脸跟踪抄过来了~可以嫖了~

**Comment by sosopop** [comment]
我只用mtcnn的onet作人脸跟踪，发现也不错。
https://github.com/zuoqing1988/ZQCNN 这里有个FacialEmotion人脸表情的模型，我拿过来后直接跑了下效果很差，您这边知道怎么搞吗

**Comment by MirrorYuChen** [comment]
你说的应该是模板匹配+onet的方案吧

**Comment by MirrorYuChen** [comment]
表情识别的效果不好，不建议使用~

**Comment by sosopop** [comment]
刚开始用模版匹配+onet，后来发现把模版匹配去掉了只用onet效果也很好

**Comment by freehawkzk** [comment]
我试了opencv里面的跟踪算法，以及Onet，最后发现还是ONet效果好一些。
