### ISSUE TITLE
请教设计模式问题

### ISSUE THREAD

**Issue by zhangluustb** [MirrorYuChen/ncnn_example#19]
` class ClassifierEngine {  `
`public:  `
`	ClassifierEngine();  `
`	~ClassifierEngine();  `
`	int LoadModel(const char* root_path);  `
`	int Classify(const cv::Mat& img_src, std::vector<ImageInfo>* images);  `
`private:  `
`	class Impl;  `
`	Impl* impl_;  `
`};  `

您好，本人才疏学浅。冒昧问一下这是一种什么设计模式呢?不直接用classifier类而用ClassifierEngine类是基于什么样的考虑呢？

**Comment by MirrorYuChen** [comment]
方便后面扩展啊，后面可能还有花的分类、食物分类等~

**Comment by MirrorYuChen** [comment]
如果有更好的方案，欢迎PR~

**Comment by MirrorYuChen** [comment]
这个项目还有些位置没有设计好，后面会继续重构~
