### ISSUE TITLE
ncnn::Mat读入后模型推断问题

### ISSUE THREAD

**Issue by taylorguo** [MirrorYuChen/ncnn_example#2]
Android里面读入bitmap转换后，ncnn无法推断：
模型用的是：https://github.com/MirrorYuChen/ncnn_106landmarks/blob/master/model/landmark.bin
https://github.com/MirrorYuChen/ncnn_106landmarks/blob/master/model/landmark.param

        AndroidBitmapInfo info;
        AndroidBitmap_getInfo(env, bitmap, &info);
        int width = info.width;
        int height = info.height;

        if (info.format != ANDROID_BITMAP_FORMAT_RGBA_8888)
            return NULL;

        void *indata;
        AndroidBitmap_lockPixels(env, bitmap, &indata);

        LOGI(" ******** JNI 图像格式转换完成");

        ncnn::Mat in;

        in = ncnn::Mat::from_pixels((const unsigned char*)indata, ncnn::Mat::PIXEL_RGBA2BGR, width, height);

        const float mean_vals[3] = {127.5, 127.5, 127.5};
        const float norm_vals[3] = {0.0078125, 0.0078125, 0.0078125};
        in.substract_mean_normalize(mean_vals, norm_vals);

        in.reshape(48, 48);
        LOGI(" ******** JNI 图像Mat已读入, 大小转换完成");

        AndroidBitmap_unlockPixels(env, bitmap);

        ncnn::Extractor ex = mtcnn->mtcnn_net.create_extractor();
        ex.set_light_mode(true);
        ex.set_num_threads(2);

        LOGI(" ******** JNI Mat Extractor 创建完成");
        ncnn::Mat output;
        ex.input("data", in);
        ex.extract("bn6_3", output);

**Comment by taylorguo** [comment]
需要用
in = ncnn::Mat::from_pixels_resize((const unsigned char*)indata, ncnn::Mat::PIXEL_BGR, width, height, 48, 48);
不能用reshape()
变换方法不同

**Comment by MirrorYuChen** [comment]
> 需要用
> in = ncnn::Mat::from_pixels_resize((const unsigned char*)indata, ncnn::Mat::PIXEL_BGR, width, height, 48, 48);
> 不能用reshape()
> 变换方法不同

老哥，你这是解决了吗？

**Comment by taylorguo** [comment]
@MirrorYuChen 问问你的看法啊，毕竟模型我没转过，ncnn也是刚上手。
我参考了ncnn里面的例子:
https://github.com/Tencent/ncnn/blob/master/examples/squeezencnn/jni/squeezencnn_jni.cpp
才接起来。
如果用了from_pixels(), 改变输入大小，要用to_pixels_resize()吗？

**Comment by MirrorYuChen** [comment]
> @MirrorYuChen 问问你的看法啊，毕竟模型我没转过，ncnn也是刚上手。
> 我参考了ncnn里面的例子:
> https://github.com/Tencent/ncnn/blob/master/examples/squeezencnn/jni/squeezencnn_jni.cpp
> 才接起来。
> 如果用了from_pixels(), 改变输入大小，要用to_pixels_resize()吗？

我如果用from_pixels，会先用opencv的resize函数，感觉opencv的resize函数比ncnn这里的from_pixels_resize接口快，问题既然已经解决了，那我关闭这个问题了哈。

**Comment by taylorguo** [comment]
ok，移动端opencv包比较大，也比较慢。

**Comment by MirrorYuChen** [comment]
> ok，移动端opencv包比较大，也比较慢。

你可以把opencv中用不到的模块去除掉，opencv就小了。

**Comment by taylorguo** [comment]
> > ok，移动端opencv包比较大，也比较慢。
> 
> 你可以把opencv中用不到的模块去除掉，opencv就小了。

好的，谢谢。

**Comment by MirrorYuChen** [comment]
> > > ok，移动端opencv包比较大，也比较慢。
> > 
> > 
> > 你可以把opencv中用不到的模块去除掉，opencv就小了。
> 
> 好的，谢谢。

没事，加油~
