### ISSUE TITLE
win10编译报了很多错误，有人遇到过吗？

### ISSUE THREAD

**Issue by deep-practice** [MirrorYuChen/ncnn_example#20]
vs2019 win32平台
![error](https://user-images.githubusercontent.com/54052915/75626530-2f831b00-5c03-11ea-8a45-416d02ddb915.png)

**Comment by MirrorYuChen** [comment]
win10上只测试过单个模块，没有测试过整个项目，你把你错误信息贴一下我看看~

**Comment by deep-practice** [comment]
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(8,1): error C2059: 语法错误:“public”
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(9,21): error C2588: “::~Landmarker”: 非法的全局 析构函数
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(9,24): error C2575: “Landmarker”: 只有成员函数和基可以是虚拟的
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(9,24): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(9,25): warning C4508: “mirror::Landmarker”: 函数应返回一个值；假定“void”返回类型
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(10,47): error C2575: “LoadModel”: 只有成员函数和基可以是虚拟的
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(10,49): error C2059: 语法错误:“常数”
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(12,62): error C2575: “ExtractKeypoints”: 只有成员函数和基可以是虚拟的
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(12,64): error C2059: 语法错误:“常数”
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(18,20): error C2143: 语法错误: 缺少“;”(在“*”的前面)
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(18,20): error C2433: “LandmarkerFactory::Landmarker”: 不允许在数据声明中使用“virtual”
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(18,20): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(18,41): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(26,12): error C2143: 语法错误: 缺少“;”(在“*”的前面)
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(26,12): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(26,32): error C2238: 意外的标记位于“;”之前
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(30,1): error C2059: 语法错误:“}”
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(30,1): error C2143: 语法错误: 缺少“;”(在“}”的前面)
1>D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\excpt.h(14,1): error C2143: 语法错误: 缺少“;”(在“{”的前面)
1>D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\excpt.h(14,1): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(1401,1): error C2143: 语法错误: 缺少“;”(在“__stdcall”的前面)
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(1401,1): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(1406,6): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(1409,27): error C2143: 语法错误: 缺少“;”(在“*”的前面)
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(1409,27): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(1409,9): error C2365: “EXCEPTION_ROUTINE”: 重定义；以前的定义是“函数”
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(1402): message : 参见“EXCEPTION_ROUTINE”的声明
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(1409,46): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(11433,31): error C3646: “Handler”: 未知重写说明符
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(11433,31): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker/zqlandmarker.h(8,40): error C2516: “mirror::Landmarker”: 是非法基类
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(9): message : 参见“mirror::Landmarker”的声明
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.cpp(5,11): error C2143: 语法错误: 缺少“;”(在“*”的前面)
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.cpp(5,11): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.cpp(5,1): error C2365: “mirror::Landmarker”: 重定义；以前的定义是“函数”
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(9): message : 参见“mirror::Landmarker”的声明
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.cpp(5,34): error C2039: “CreateLandmarker”: 不是“ZQLandmarkerFactory”的成员
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.h(23): message : 参见“ZQLandmarkerFactory”的声明
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.cpp(5,53): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.cpp(5,53): error C2059: 语法错误:“{”
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.cpp(5,53): error C2143: 语法错误: 缺少“;”(在“{”的前面)
1>D:\compile\ncnn_example-master\src\face\landmarker\landmarker.cpp(5,53): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>zqlandmarker.cpp
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(8,1): error C2059: 语法错误:“public”
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(9,21): error C2588: “::~Landmarker”: 非法的全局 析构函数
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(9,24): error C2575: “Landmarker”: 只有成员函数和基可以是虚拟的
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(9,24): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(9,25): warning C4508: “mirror::Landmarker”: 函数应返回一个值；假定“void”返回类型
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(10,47): error C2575: “LoadModel”: 只有成员函数和基可以是虚拟的
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(10,49): error C2059: 语法错误:“常数”
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(12,62): error C2575: “ExtractKeypoints”: 只有成员函数和基可以是虚拟的
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(12,64): error C2059: 语法错误:“常数”
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(18,20): error C2143: 语法错误: 缺少“;”(在“*”的前面)
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(18,20): error C2433: “LandmarkerFactory::Landmarker”: 不允许在数据声明中使用“virtual”
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(18,20): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(18,41): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(26,12): error C2143: 语法错误: 缺少“;”(在“*”的前面)
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(26,12): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(26,32): error C2238: 意外的标记位于“;”之前
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(30,1): error C2059: 语法错误:“}”
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(30,1): error C2143: 语法错误: 缺少“;”(在“}”的前面)
1>D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\excpt.h(14,1): error C2143: 语法错误: 缺少“;”(在“{”的前面)
1>D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\excpt.h(14,1): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(1401,1): error C2143: 语法错误: 缺少“;”(在“__stdcall”的前面)
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(1401,1): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(1406,6): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(1409,27): error C2143: 语法错误: 缺少“;”(在“*”的前面)
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(1409,27): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(1409,9): error C2365: “EXCEPTION_ROUTINE”: 重定义；以前的定义是“函数”
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(1402): message : 参见“EXCEPTION_ROUTINE”的声明
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(1409,46): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(11433,31): error C3646: “Handler”: 未知重写说明符
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(11433,31): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\zqlandmarker.h(8,40): error C2516: “mirror::Landmarker”: 是非法基类
1>D:\compile\ncnn_example-master\src\face\landmarker\zqlandmarker\../landmarker.h(9): message : 参见“mirror::Landmarker”的声明

**Comment by deep-practice** [comment]
代码结构感觉挺好的，准备模仿你这个写个tensorrt的。。

**Comment by deep-practice** [comment]
错误出现在class FaceEngine::Impl这个实现里面

**Comment by MirrorYuChen** [comment]
这个应该路径问题，visual studio上编译，关于头文件包含，及库链接，估计要有绝对路径，你把里面CMakeLists.txt，及相对路径改一下估计就可以了，我有时间也看看怎么支持windows

**Comment by MirrorYuChen** [comment]
等着看你的project啦，等我把ncnn代码学习完，也会去学习一下tensorRT，到时候就学习你的project啦！

**Comment by deep-practice** [comment]
我把common.h和face_engine.h里面的namespace注释掉就可以了。。。

**Comment by gjj123** [comment]
VS2015 64 同上错误，无法编译

**Comment by Dreak096** [comment]
所以有解决方案吗
