### ISSUE TITLE
Upload models at another place

### ISSUE THREAD

**Issue by mostafaSataki** [MirrorYuChen/ncnn_example#21]
Hi.
Please upload models at another place such google drive.
Thanks.

**Comment by MirrorYuChen** [comment]
ok, I'll provide upload models at google drive later.

**Comment by MirrorYuChen** [comment]
I am so sorry, I can't access google now.

**Comment by grdsvt** [comment]
Hi, I have the same problem.....
Is not possible download the model.....can you give other link?
Thanks

**Comment by MirrorYuChen** [comment]
I have upload to google, please refer to readme.
