### ISSUE TITLE
Face landmarks are incorrectly positioned

### ISSUE THREAD

**Issue by GeneralJing** [MirrorYuChen/ncnn_example#23]
I use the code and model link files provided in the CSDN blog。But when I run the code, the face landmarks are incorrectly positioned.
![result](https://user-images.githubusercontent.com/6658900/77156161-c2fc8d00-6ad9-11ea-8b39-46735d0ce969.jpg)

**Comment by GeneralJing** [comment]
Is it a problem with the ncnn model？

**Comment by MirrorYuChen** [comment]
You can  check, according to my test code: src/face/test_face.cpp

**Comment by MirrorYuChen** [comment]
The input of the landmarker detecter must be a face, not a fully picture.

**Comment by MirrorYuChen** [comment]
The bad usage brings out error result.

**Comment by GeneralJing** [comment]
I understand. In the whole image, I can detect faces normally using the method you mentioned above, but there is a false detection. I will look at other details.Thank you.

**Comment by MirrorYuChen** [comment]
OK，You are welcome~If you have any question, you can pull an issue,
~
