### ISSUE TITLE
TestRecognize

### ISSUE THREAD

**Issue by jackim** [MirrorYuChen/ncnn_example#25]
在testrecognize中，没有人脸对齐，直接进行了特征提取进行比对。应该还需要加人脸对齐吧。其次retinaface人脸检测 本身会返回5个关键点，没必现格外的模型提取了吧，是否支持。

**Comment by MirrorYuChen** [comment]
这个对齐可以自己加，单元测试需要尽量去藕合，这些只是写的一些单元测试程序。然后关键点这块，五点就够用了，如果有需要，我这周周末加一下，其实也不难，如果你改好了也可以PR，欢迎PR啊，大家一起来维护这个项目

**Comment by jackim** [comment]
腾讯ncnn的样例有retinaface的demo，里面包含了关键点的提取。

**Comment by MirrorYuChen** [comment]
这个我知道，加一下很容易，只是没加而言~
