### ISSUE TITLE
code version 935b49af have link error

### ISSUE THREAD

**Issue by freehawkzk** [MirrorYuChen/ncnn_example#26]
i cloned the lastest version of code from github.
i installed protobuf,cmake(3.10.0),opencv(4.3.0) on my ubuntu18.04.
i compile the project by mkdir build && cd build && cmake .. && make -j8
then i got this information:
/usr/bin/ld: ../../src/../lib/libncnn.a(mat.cpp.o)：普通ELF重定位（M: 183）
/usr/bin/ld: ../../src/../lib/libncnn.a(mat.cpp.o)：普通ELF重定位（M: 183）
/usr/bin/ld: ../../src/../lib/libncnn.a(mat.cpp.o)：普通ELF重定位（M: 183）
/usr/bin/ld: ../../src/../lib/libncnn.a(mat.cpp.o)：普通ELF重定位（M: 183）
../../src/../lib/libncnn.a: 无法添加符号: 文件格式错误
collect2: error: ld returned 1 exit status
src/CMakeFiles/classifier.dir/build.make:147: recipe for target 'src/classifier' failed
make[2]: *** [src/classifier] Error 1
CMakeFiles/Makefile2:91: recipe for target 'src/CMakeFiles/classifier.dir/all' failed
make[1]: *** [src/CMakeFiles/classifier.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
/usr/bin/ld: ../../src/../lib/libncnn.a(mat.cpp.o)：普通ELF重定位（M: 183）
/usr/bin/ld: ../../src/../lib/libncnn.a(mat.cpp.o)：普通ELF重定位（M: 183）
/usr/bin/ld: ../../src/../lib/libncnn.a(mat.cpp.o)：普通ELF重定位（M: 183）
/usr/bin/ld: ../../src/../lib/libncnn.a(mat.cpp.o)：普通ELF重定位（M: 183）
../../src/../lib/libncnn.a: 无法添加符号: 文件格式错误
collect2: error: ld returned 1 exit status
src/CMakeFiles/object.dir/build.make:147: recipe for target 'src/object' failed
make[2]: *** [src/object] Error 1
CMakeFiles/Makefile2:202: recipe for target 'src/CMakeFiles/object.dir/all' failed
make[1]: *** [src/CMakeFiles/object.dir/all] Error 2
/usr/bin/ld: ../../src/../lib/libncnn.a(mat.cpp.o)：普通ELF重定位（M: 183）
/usr/bin/ld: ../../src/../lib/libncnn.a(mat.cpp.o)：普通ELF重定位（M: 183）
/usr/bin/ld: ../../src/../lib/libncnn.a(mat.cpp.o)：普通ELF重定位（M: 183）
/usr/bin/ld: ../../src/../lib/libncnn.a(mat.cpp.o)：普通ELF重定位（M: 183）
../../src/../lib/libncnn.a: 无法添加符号: 文件格式错误
collect2: error: ld returned 1 exit status
src/CMakeFiles/face.dir/build.make:147: recipe for target 'src/face' failed
make[2]: *** [src/face] Error 1
CMakeFiles/Makefile2:128: recipe for target 'src/CMakeFiles/face.dir/all' failed
make[1]: *** [src/CMakeFiles/face.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

it seems like something wrong with ncnn.

then i compiled ncnn by myself, and edit CMakeLists.txt for scr folder like this:
#file(GLOB LIBS ${CMAKE_CURRENT_SOURCE_DIR}/../lib/*.a)
target_link_libraries(VisionEngine PUBLIC ${LIBS} ${OpenCV_LIBS} ncnn)

everything goes ok.

because i have no vulkan sdk installed, so i edit the ncnn/alloctor.h line 29 "#undef NCNN_VULKAN"

**Comment by MirrorYuChen** [comment]
you need build ncnn lib on your system, than replace the ncnn lib of the ncnn_example project,

**Comment by MirrorYuChen** [comment]
说英语难受啊，直接说汉语吧，都是中国人。

**Comment by MirrorYuChen** [comment]
项目里面的ncnn库是在我的系统上编译的，你把你系统上编译的ncnn库编译好，拿过来替换一下就行了。

**Comment by freehawkzk** [comment]
恩，我后来用自己编译的ncnn时，挺好的。
