### ISSUE TITLE
it goes wrong when i do not install vulkan?

### ISSUE THREAD

**Issue by githubtianya** [MirrorYuChen/ncnn_example#28]
it got: fatal error: vulkan/vulkan.h, do i must install vulkan?

**Comment by MirrorYuChen** [comment]
https://github.com/MirrorYuChen/ncnn_example/issues/26

**Comment by MirrorYuChen** [comment]
please refer to issue 26

**Comment by MirrorYuChen** [comment]
在你的系统上重新编译ncnn，然后替换掉项目中的ncnn库就好了~

**Comment by MirrorYuChen** [comment]
使用的时候，如果没有用Vulkan，将对应cmakelists.txt文件中的vulkan开关关闭。
