### ISSUE TITLE
RatioAnchors 函数几个问题

### ISSUE THREAD

**Issue by KangLin** [MirrorYuChen/ncnn_example#29]
1. int RatioAnchors(const cv::Rect & anchor,
2. 	const std::vector<float>& ratios, 
3. 	std::vector<cv::Rect>* anchors) {
4. 	anchors->clear();
5. 	cv::Point center = cv::Point(anchor.x + (anchor.width - 1) * 0.5f,
6. 		anchor.y + (anchor.height - 1) * 0.5f);
7. 	float anchor_size = anchor.width * anchor.height;
8. #if defined(_OPENMP)
9. #pragma omp parallel for num_threads(threads_num)
10. #endif
11. 	for (int i = 0; i < static_cast<int>(ratios.size()); ++i) {
12. 		float ratio = ratios.at(i);
13. 		float anchor_size_ratio = anchor_size / ratio;
14. 		float curr_anchor_width = std::sqrt(anchor_size_ratio);
15. 		float curr_anchor_height = curr_anchor_width * ratio;
16. 		float curr_x = center.x - (curr_anchor_width - 1)* 0.5f;
17. 		float curr_y = center.y - (curr_anchor_height - 1)* 0.5f;
18. 
19. 		cv::Rect curr_anchor = cv::Rect(curr_x, curr_y,
20. 			curr_anchor_width - 1, curr_anchor_height - 1);
21. 		anchors->push_back(curr_anchor);
22. 	}
23. 	return 0;
24. }
25. 

有以下几个问题：
1.  第5行，取中点，为什么宽度要减1？
2.  第15行，curr_anchor_height为什么不是 curr_anchor_height=curr_anchor_width ?
3.  13到15行，计算高宽是否下面算法更好？

       curr_anchor_width=anchor.width/ratio
       curr_anchor_height=anchor.height;/ratio

**Comment by MirrorYuChen** [comment]
这个可能你需要补充一下RPN相关知识~

**Comment by KangLin** [comment]
请给个相关知识的链接

**Comment by MirrorYuChen** [comment]
你找一下对应人脸检测器论文呗，里面应该有描述。之所以减1的原因是，你坐标是从0开始计数，需要减去1.
