### ISSUE TITLE
视频抖动太严重，有什么好的建议吗？

### ISSUE THREAD

**Issue by JackLongKing** [MirrorYuChen/ncnn_example#3]
目前将mtcnn和该项目的关键点结合了起来，在启动摄像头测试视频时，发现抖动十分严重，但mtcnn的5个关键点很稳定。所以想问问您，有什么好的建议可以改进一下？

**Comment by JackLongKing** [comment]
猜测跟均值mean_val和方差std有关，想问一下您训练时的均值和方差分别是127.5f和0.0078125f吗？

**Comment by JackLongKing** [comment]
根据观察，抖动很大程度上是检测抖动所引起的。

**Comment by MirrorYuChen** [comment]
可以加一个高斯滤波做一个平滑处理~
