### ISSUE TITLE
编译时link出错

### ISSUE THREAD

**Issue by dianxin556** [MirrorYuChen/ncnn_example#30]
按照readme，编译时，报错：
/usr/bin/ld: ../../src/../lib/libncnn.a(mat.cpp.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: ../../src/../lib/libncnn.a(mat.cpp.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: ../../src/../lib/libncnn.a(mat.cpp.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: ../../src/../lib/libncnn.a(mat.cpp.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: ../../src/../lib/libncnn.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/face.dir/build.make:105: src/face] Error 1
make[1]: *** [CMakeFiles/Makefile2:134: src/CMakeFiles/face.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

有人遇到吗？单独进src，make可以生成库，但是在ncnn-example 路径下make，就出错了，不知道是哪里路径不对

**Comment by MirrorYuChen** [comment]
https://github.com/MirrorYuChen/ncnn_example/issues/26

**Comment by MirrorYuChen** [comment]
看一下这个issue

**Comment by MirrorYuChen** [comment]
我突然发现你这个问题是对cmake不熟悉的原因，建议看一下cmake的基本语法，然后研究一下CMakeLists.txt文件。

**Comment by dianxin556** [comment]
多谢回复，是的。后来我也找到了原因，确实是CMAKE不熟，路径什么搞不清楚
