### ISSUE TITLE
NMS的问题

### ISSUE THREAD

**Issue by BrownOfSummer** [MirrorYuChen/ncnn_example#34]
NMS的时候采用了升序排列，最后检测出来的人脸是置信度最低的进行主导的，是不是有问题

**Comment by MirrorYuChen** [comment]
你再确认一下，    std::sort(inputs_tmp.begin(), inputs_tmp.end(),
    [](const T& a, const T& b) {
        return a.score_ < b.score_;
    });
这个是降序排列。

**Comment by MirrorYuChen** [comment]
小于的时候，会做元素交换，所以最终得到由大到小顺序的数组。

**Comment by MirrorYuChen** [comment]
好吧，好像我搞错了，你能提个PR修一下吗？

**Comment by MirrorYuChen** [comment]
我自己修一下吧，感谢！

**Comment by MirrorYuChen** [comment]
已经修复~
