### ISSUE TITLE
insightface 106 landmarks测试效果很一般啊

### ISSUE THREAD

**Issue by oopming** [MirrorYuChen/ncnn_example#36]
如题

**Comment by MirrorYuChen** [comment]
你可以根据他提供的python文件，把预处理功能加上

**Comment by MirrorYuChen** [comment]
我这边就是跑着玩了一下，最近没怎么搞人脸相关的工作，就是测试了一下。

**Comment by MirrorYuChen** [comment]
我加了一下预处理，不知道好点了没，你有时间测试一下呗

**Comment by HeshanMountteen** [comment]
> 我加了一下预处理，不知道好点了没，你有时间测试一下呗

您好，请问您的这一步预处理该放在哪里？我的理解是放在推理输入之前，先preProcess再exec->in，exec->output，可是得到的output里坐标都是NaN欸
