### ISSUE TITLE
请问有模型转换的代码吗？

### ISSUE THREAD

**Issue by ZZHHogan** [MirrorYuChen/ncnn_example#38]
你好，请问有模型转换的代码吗？这边希望在您的项目基础上，转换自己训练好的模型（比如yolo）

**Comment by ChenjingYu1993** [comment]
ncnn项目提供了转换工具呀，直接编译一下ncnn源码就有了

**Comment by MirrorYuChen** [comment]
去看一下ncnn的wiki就知道了！

**Comment by ZZHHogan** [comment]
你好，感谢回答。可是我使用pth转onnx，再将onnx转成ncnn的时候报错。 类似以下的命令： .\onnx2ncnn.exe  yolov4.onnx  ncnn.param ncnn.bin
![image](https://user-images.githubusercontent.com/40531744/92568078-34f7a700-f2b1-11ea-9c70-824f215e361b.png)
![image](https://user-images.githubusercontent.com/40531744/92568099-3d4fe200-f2b1-11ea-9e57-e5774bd57940.png)
我所使用的版本为： pytorch版本为1.6， onnx版本为1.6 操作系统为win10，使用onnxsim简化onnx后还是出现一样的错误。请问是什么原因呢？以及如何解决？

**Comment by ZZHHogan** [comment]
> 去看一下ncnn的wiki就知道了！

你好，感谢回答。可是我使用pth转onnx，再将onnx转成ncnn的时候报错。 类似以下的命令： .\onnx2ncnn.exe yolov4.onnx ncnn.param ncnn.bin
image
image
我所使用的版本为： pytorch版本为1.6， onnx版本为1.6 操作系统为win10，使用onnxsim简化onnx后还是出现一样的错误。请问是什么原因呢？以及如何解决？

**Comment by MirrorYuChen** [comment]
这个问题去ncnn项目提会更合适~

**Comment by MirrorYuChen** [comment]
https://github.com/Tencent/ncnn/issues/1885

**Comment by ZZHHogan** [comment]
> 这个问题去ncnn项目提会更合适~

好的，谢谢，我也已经在ncnn上提问了，感谢你的回答~

**Comment by MirrorYuChen** [comment]
欢迎加入ncnn大家庭！
