### ISSUE TITLE
WorKing on TX2

### ISSUE THREAD

**Issue by zhuyu-cs** [MirrorYuChen/ncnn_example#4]
Hello, I think your project on Nano is working on CPU, I try to inference on GPU, but it does not work.  Just like ncnn：

ncnn::create_gpu_instance();
{

}
ncnn::destroy_gpu_instance();

Do you know how to fix it？

**Comment by MirrorYuChen** [comment]
sorry, my fault.  I build ncnn with vulkan,  I'll try to test vulkan version.

**Comment by MirrorYuChen** [comment]
I have add the vulkan demo， you can test now.

**Comment by MirrorYuChen** [comment]
the detail you can refer to ncnn wiki：
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-vulkan

**Comment by zhuyu-cs** [comment]
Oh,thansks, I have worked out , but while I using GPU for inference, 0 faces detected, the cpu was ok, very strange.
And I tested your code , the same probolem come up.

**Comment by MirrorYuChen** [comment]
Have you verified whether you have compiled vulkan ncnn successed?

**Comment by zhuyu-cs** [comment]
> Have you verified whether you have compiled vulkan ncnn successed?

Yeah，I am sure I have compiled vulkan ncnn succeed.

**Comment by MirrorYuChen** [comment]
perhaps， there are some diffence between jetson nano and tx2， you need to replace your libncnn.a in the folder lib

**Comment by zhuyu-cs** [comment]
> perhaps， there are some diffence between jetson nano and tx2， you need to replace your libncnn.a in the folder lib

I did it，but there was no effect.

**Comment by MirrorYuChen** [comment]
can you provide your print informations?

**Comment by zhuyu-cs** [comment]
> can you provide your print informations?
[0 NVIDIA Tegra X2 (nvgpu)] queueC=0[16] queueT=0[16] memU=2 memDL=2 memHV=2
[0 NVIDIA Tegra X2 (nvgpu)] fp16p=1 fp16s=1 fp16a=0 int8s=0 int8a=0
start face detect.
0 faces detected.

**Comment by MirrorYuChen** [comment]
here is my print information:
‘{19-07-27 12:28}mirror:~/workspace/ncnn_106landmarks/build@master✗✗✗✗✗✗ mirror% ./main 
[0 NVIDIA Tegra X1 (nvgpu)]  queueC=0[16]  queueT=0[16]  memU=2  memDL=2  memHV=2
[0 NVIDIA Tegra X1 (nvgpu)]  fp16p=1  fp16s=1  fp16a=0  int8s=1  int8a=0
start face detect.
4 faces detected.
start extract feature.
extract feature end.
start extract feature.
extract feature end.
similarity is: 0.358641’
I have no tx2， it's too expensive for me, I think you need to test other vulkan ncnn example to check whether it works.

**Comment by MirrorYuChen** [comment]
my ncnn is the newest master branch, you can try to replace the newest ncnn version.

**Comment by zhuyu-cs** [comment]
OK，thank you very much！

**Comment by MirrorYuChen** [comment]
Good Luck~
