### ISSUE TITLE
/usr/bin/ld: cannot open output file face: Is a directory

### ISSUE THREAD

**Issue by yisampi** [MirrorYuChen/ncnn_example#40]
(base) [ncnn_example-master]$ make
Scanning dependencies of target VisionEngine
[  3%] Building CXX object src/CMakeFiles/VisionEngine.dir/classifier/classifier/mobilenet/mobilenet.cpp.o
[  6%] Building CXX object src/CMakeFiles/VisionEngine.dir/classifier/classifier_engine.cpp.o
[ 10%] Building CXX object src/CMakeFiles/VisionEngine.dir/classifier/test_classifier.cpp.o
[ 13%] Building CXX object src/CMakeFiles/VisionEngine.dir/common/common.cpp.o
[ 16%] Building CXX object src/CMakeFiles/VisionEngine.dir/face/aligner/aligner.cpp.o
[ 20%] Building CXX object src/CMakeFiles/VisionEngine.dir/face/database/face_database.cpp.o
[ 23%] Building CXX object src/CMakeFiles/VisionEngine.dir/face/database/stream/file_stream.cpp.o
[ 26%] Building CXX object src/CMakeFiles/VisionEngine.dir/face/detecter/anticonv/anticonv.cpp.o
[ 30%] Building CXX object src/CMakeFiles/VisionEngine.dir/face/detecter/centerface/centerface.cpp.o
[ 33%] Building CXX object src/CMakeFiles/VisionEngine.dir/face/detecter/detecter.cpp.o
[ 36%] Building CXX object src/CMakeFiles/VisionEngine.dir/face/detecter/mtcnn/mtcnn.cpp.o
[ 40%] Building CXX object src/CMakeFiles/VisionEngine.dir/face/detecter/retinaface/retinaface.cpp.o
[ 43%] Building CXX object src/CMakeFiles/VisionEngine.dir/face/face_engine.cpp.o
[ 46%] Building CXX object src/CMakeFiles/VisionEngine.dir/face/landmarker/insightface/insightface.cpp.o
[ 50%] Building CXX object src/CMakeFiles/VisionEngine.dir/face/landmarker/landmarker.cpp.o
[ 53%] Building CXX object src/CMakeFiles/VisionEngine.dir/face/landmarker/zqlandmarker/zqlandmarker.cpp.o
[ 56%] Building CXX object src/CMakeFiles/VisionEngine.dir/face/recognizer/mobilefacenet/mobilefacenet.cpp.o
[ 60%] Building CXX object src/CMakeFiles/VisionEngine.dir/face/recognizer/recognizer.cpp.o
[ 63%] Building CXX object src/CMakeFiles/VisionEngine.dir/face/test_face.cpp.o
[ 66%] Building CXX object src/CMakeFiles/VisionEngine.dir/face/tracker/tracker.cpp.o
[ 70%] Building CXX object src/CMakeFiles/VisionEngine.dir/object/object/mobilenetssd/mobilenetssd.cpp.o
[ 73%] Building CXX object src/CMakeFiles/VisionEngine.dir/object/object_engine.cpp.o
[ 76%] Building CXX object src/CMakeFiles/VisionEngine.dir/object/test_object.cpp.o
[ 80%] Linking CXX static library libVisionEngine.a
[ 80%] Built target VisionEngine
Scanning dependencies of target face
[ 83%] Building CXX object src/CMakeFiles/face.dir/face/test_face.cpp.o
[ 86%] Linking CXX executable face
/usr/bin/ld: cannot open output file face: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [src/face] Error 1
make[1]: *** [src/CMakeFiles/face.dir/all] Error 2
make: *** [all] Error 2

**Comment by MirrorYuChen** [comment]
有没有将ncnn库更换为你当前系统编译出来的库？

**Comment by yisampi** [comment]
替换了libncnn.a和include/ncnn/

**Comment by MirrorYuChen** [comment]
是按照前面readme里面的步骤编译的吗？

**Comment by MirrorYuChen** [comment]
是不是权限问题？你sudo加一下权限试试

**Comment by MirrorYuChen** [comment]
sudo chmod -R 777 ./

**Comment by yisampi** [comment]
权限没有问题呢

**Comment by yisampi** [comment]
编译成功了，是我之前编译的方法错了
