### ISSUE TITLE
MacOS Catalina 10.15.5 error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by Headera** [MirrorYuChen/ncnn_example#41]
make -j 3
[  3%] Building CXX object src/CMakeFiles/VisionEngine.dir/classifier/test_classifier.cpp.o
[ 10%] Building CXX object src/CMakeFiles/VisionEngine.dir/classifier/classifier/mobilenet/mobilenet.cpp.o
[ 10%] Building CXX object src/CMakeFiles/VisionEngine.dir/classifier/classifier_engine.cpp.o
clangclangclang: : : error: unsupported option '-fopenmp'errorerror
: : unsupported option '-fopenmp'unsupported option '-fopenmp'

make[2]: *** [src/CMakeFiles/VisionEngine.dir/classifier/test_classifier.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/CMakeFiles/VisionEngine.dir/classifier/classifier_engine.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/VisionEngine.dir/classifier/classifier/mobilenet/mobilenet.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/VisionEngine.dir/all] Error 2
make: *** [all] Error 2

**Comment by MirrorYuChen** [comment]
没有用过MAC，好像是可以用openmp的，你去ncnn的wiki上看一下

**Comment by MirrorYuChen** [comment]
你也可以把相关openmp的部分注释掉，应该就可以编译通过了

**Comment by MirrorYuChen** [comment]
直接把src下的CMakeLists.txt中的-fopenmp删掉就好了

**Comment by MirrorYuChen** [comment]
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -O2 -fPIC -std=c++11 -fopenmp")
替换成：
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -O2 -fPIC -std=c++11")
