### ISSUE TITLE
Are there any good Gender&Age pretained models Available on ncnn?

### ISSUE THREAD

**Issue by songinmok63** [MirrorYuChen/ncnn_example#42]
Thank you so much for your contribution.
Are there any good Gender&Age pertained models available on ncnn?
I have GA112-100.nchwbin, GA112.zqparams, how to convert them to ncnn models?

**Comment by MirrorYuChen** [comment]
I am so sorry, I have not  used.

**Comment by MirrorYuChen** [comment]
zqcnn is  a very worth learning project. I will learn it later.
