### ISSUE TITLE
mobilefacenet的模型是从哪个原始模型转过来的

### ISSUE THREAD

**Issue by sosopop** [MirrorYuChen/ncnn_example#43]
之前用这个项目做的人脸识别，现在想转到TNN，但是收集的一些人脸特征不想丢弃，想用原始模型转到tnn模型。这样就不用丢掉以前收集的特征数据了。

**Comment by MirrorYuChen** [comment]
这谁记得起来啊，应该是insightface上找的

**Comment by sosopop** [comment]
insightface上的试过了，转到ncnn模型输出结果和这个项目里的用的结果不一样，我再找找吧

**Comment by sosopop** [comment]
https://github.com/Tencent/ncnn/issues/742
搜到一个你发的文章，还能帮你回忆起来吗

**Comment by MirrorYuChen** [comment]
你平时问别人问题都是这样问的？社区现在都这个风气？

**Comment by sosopop** [comment]
我哪里冒犯到你了吗？你想要什么语气，我可以装一下。

**Comment by h3clikejava** [comment]
> 我哪里冒犯到你了吗？你想要什么语气，我可以装一下。

朋友你搞定没？我遇到跟你一样的需求了

**Comment by sosopop** [comment]
@h3clikejava TNN可以直接加载NCNN模型，不过项目中用到的这些都还没加载成功过。
