### ISSUE TITLE
How to get landmark from "RetinafaceFactory"

### ISSUE THREAD

**Issue by hongson23** [MirrorYuChen/ncnn_example#44]
Hello @MirrorYuChen,
Thank you for yours work!

I would like to get landmarks from retina face detection, I saw that the landmarks was extract from model "ex.extract(landmark_layer_name.c_str(), landmark_mat);"
So how to calculate and store landmark to face_info.keypoints ?

**Comment by MirrorYuChen** [comment]
I will add the process code this week.

**Comment by MirrorYuChen** [comment]
Done! please refer to the newest code.

**Comment by hongson23** [comment]
> Done! please refer to the newest code.

Thank you so much @MirrorYuChen,
Retina face works perfectly, bbox and landmarks were extract fast and accurately!
