### ISSUE TITLE
Can not build cmake, error can not find -lncnn

### ISSUE THREAD

**Issue by defi0x1** [MirrorYuChen/ncnn_example#45]
Hi Author, Thank for your work. I have a problem when build this source to test face mask detection.
My Steps:
~ mkdir build
~ cd build 
~ cmake ..
~ make -j3
And have message show to me this error. Could you help me ?
Thanks !
![Screenshot from 2020-11-06 09-09-49](https://user-images.githubusercontent.com/34453681/98317874-f3188200-200f-11eb-9827-bbebf999879f.png)

**Comment by MirrorYuChen** [comment]
You need replace ncnn lib compiled on you sysrem.

**Comment by defi0x1** [comment]
Thanks ! It work !
