### ISSUE TITLE
SigArt error

### ISSUE THREAD

**Issue by MyraBaba** [MirrorYuChen/ncnn_example#46]
Hi,

I compiled the project but face is crashing at below screenshot point.

ex.extract(class...) at stride8

any idea ? 

<img width="1140" alt="Screen Shot 2021-01-08 at 14 08 47" src="https://user-images.githubusercontent.com/17505439/104008917-3aabbd80-51bb-11eb-8f28-c70de7642a4a.png">

**Comment by MyraBaba** [comment]
@MirrorYu  any idea ?

**Comment by MirrorYuChen** [comment]
Please provide information of compile system and  ncnn version.

**Comment by MirrorYu** [comment]
测试一切正常，没有提供任何额外信息，无法帮助定位问题。
