### ISSUE TITLE
mask detection error 

### ISSUE THREAD

**Issue by XuanLi728** [MirrorYuChen/ncnn_example#47]
大佬抱歉麻烦您了，我的平台是 ubuntu 18.04LTS, NCNN 是最新的那一版本，请问为什么测试的口罩识别功能无法正常工作呢？
![mask_result](https://user-images.githubusercontent.com/38834684/105018711-467f6580-5a80-11eb-9c77-9cfe8ebfa032.jpg)

**Comment by XuanLi728** [comment]
这个版本的口罩识别能用，待我这个菜鸡Debug 或者大佬亲自下场hhhh
https://github.com/MirrorYuChen/ncnn_example/tree/53f9319d393e7ca872a3e5f5881b8408c43a26ca

![mask_result](https://user-images.githubusercontent.com/38834684/105022142-5d27bb80-5a84-11eb-998a-9e5b916be3e6.jpg)

**Comment by MirrorYuChen** [comment]
新版本还没测试过，不是很清楚，等我有空我测试一下哈~

**Comment by MirrorYuChen** [comment]
你有时间测试一下旧的2020年版本看看是否正常，ncnn迭代太快了，还没有跟上~

**Comment by MirrorYuChen** [comment]
20200226

**Comment by XuanLi728** [comment]
OK, 我编译下看看怎么回事

**Comment by XuanLi728** [comment]
ncnn-20200226  Cmake 参数 cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_BUILD_EXAMPLES=ON ..
ncnn_example 最新版本
平台信息: 
x86 架构

![Screenshot from 2021-01-20 20-19-04](https://user-images.githubusercontent.com/38834684/105173981-c975ee00-5b5c-11eb-8a6d-0d05071f9512.png)

口罩检测还是失败了

![mask_result](https://user-images.githubusercontent.com/38834684/105174103-05a94e80-5b5d-11eb-9bbc-7b0b42f54f06.jpg)

**Comment by MirrorYuChen** [comment]
周末我看一下，之前在我的Jetson Nano上测试是没问题的

**Comment by MirrorYu** [comment]
需要切换一下人脸检测器到anticonv，默认的是retinaface

**Comment by MirrorYu** [comment]
/home/mirror/Desktop/Screenshot from 2021-01-24 03-03-36.png

**Comment by MirrorYu** [comment]
![Uploading Screenshot from 2021-01-24 03-03-36.png…]()

**Comment by MirrorYu** [comment]
具体在face_engine.cpp的第16和17行，应该能够整明白
