### ISSUE TITLE
not support the latest NCNN?

### ISSUE THREAD

**Issue by MichaelXin** [MirrorYuChen/ncnn_example#51]
Great work !
I tested the examples using NCNN version 20200226. 
It runs smoothly.  
But it seems that the latest NCNN, say version 20210525, is not supported.
So d you have any plan to update the code and support the new NCNN?

**Comment by MirrorYuChen** [comment]
I will test the new NCNN when i am free.

**Comment by MirrorYuChen** [comment]
In fact, all is work well. my compiler is visual studio 2017(win7)

**Comment by MirrorYuChen** [comment]
I will update my compiled lib

**Comment by MirrorYuChen** [comment]
为了方便处理，我把ncnn的源码直接放项目中了，你可以直接源码编译看看，这里需要手动在脚本里面指定protobuf的路径
