### ISSUE TITLE
How to calculate the similarity(score) of arcface in the insightface github?

### ISSUE THREAD

**Issue by songinmok63** [MirrorYuChen/ncnn_example#52]
Thank you so much for your contribution.

How to calculate the similarity or score between two features ?

7767517
154 178
Input                    input.1                  0 1 input.1
Convolution              Conv_0                   1 1 input.1 684 0=64 1=3 4=1 5=1 6=1728
PReLU                    PRelu_1                  1 1 684 479 0=64
Split                    splitncnn_0              1 2 479 479_splitncnn_0 479_splitncnn_1
BatchNorm                BatchNormalization_2     1 1 479_splitncnn_1 480 0=64
Convolution              Conv_3                   1 1 480 687 0=64 1=3 4=1 5=1 6=36864
PReLU                    PRelu_4                  1 1 687 484 0=64
Convolution              Conv_5                   1 1 484 690 0=64 1=3 3=2 4=1 5=1 6=36864
Convolution              Conv_6                   1 1 479_splitncnn_0 693 0=64 1=1 3=2 5=1 6=4096
BinaryOp                 Add_7                    2 1 690 693 489
Split                    splitncnn_1              1 2 489 489_splitncnn_0 489_splitncnn_1
BatchNorm                BatchNormalization_8     1 1 489_splitncnn_1 490 0=64
Convolution              Conv_9                   1 1 490 696 0=64 1=3 4=1 5=1 6=36864
PReLU                    PRelu_10                 1 1 696 494 0=64
Convolution              Conv_11                  1 1 494 699 0=64 1=3 4=1 5=1 6=36864
BinaryOp                 Add_12                   2 1 699 489_splitncnn_0 497
Split                    splitncnn_2              1 2 497 497_splitncnn_0 497_splitncnn_1
BatchNorm                BatchNormalization_13    1 1 497_splitncnn_1 498 0=64
Convolution              Conv_14                  1 1 498 702 0=64 1=3 4=1 5=1 6=36864
PReLU                    PRelu_15                 1 1 702 502 0=64
Convolution              Conv_16                  1 1 502 705 0=64 1=3 4=1 5=1 6=36864
BinaryOp                 Add_17                   2 1 705 497_splitncnn_0 505
Split                    splitncnn_3              1 2 505 505_splitncnn_0 505_splitncnn_1
BatchNorm                BatchNormalization_18    1 1 505_splitncnn_1 506 0=64
Convolution              Conv_19                  1 1 506 708 0=128 1=3 4=1 5=1 6=73728
PReLU                    PRelu_20                 1 1 708 510 0=128
Convolution              Conv_21                  1 1 510 711 0=128 1=3 3=2 4=1 5=1 6=147456
Convolution              Conv_22                  1 1 505_splitncnn_0 714 0=128 1=1 3=2 5=1 6=8192
BinaryOp                 Add_23                   2 1 711 714 515
Split                    splitncnn_4              1 2 515 515_splitncnn_0 515_splitncnn_1
BatchNorm                BatchNormalization_24    1 1 515_splitncnn_1 516 0=128
Convolution              Conv_25                  1 1 516 717 0=128 1=3 4=1 5=1 6=147456
PReLU                    PRelu_26                 1 1 717 520 0=128
Convolution              Conv_27                  1 1 520 720 0=128 1=3 4=1 5=1 6=147456
BinaryOp                 Add_28                   2 1 720 515_splitncnn_0 523
Split                    splitncnn_5              1 2 523 523_splitncnn_0 523_splitncnn_1
BatchNorm                BatchNormalization_29    1 1 523_splitncnn_1 524 0=128
Convolution              Conv_30                  1 1 524 723 0=128 1=3 4=1 5=1 6=147456
PReLU                    PRelu_31                 1 1 723 528 0=128
Convolution              Conv_32                  1 1 528 726 0=128 1=3 4=1 5=1 6=147456
BinaryOp                 Add_33                   2 1 726 523_splitncnn_0 531
Split                    splitncnn_6              1 2 531 531_splitncnn_0 531_splitncnn_1
BatchNorm                BatchNormalization_34    1 1 531_splitncnn_1 532 0=128
Convolution              Conv_35                  1 1 532 729 0=128 1=3 4=1 5=1 6=147456
PReLU                    PRelu_36                 1 1 729 536 0=128
Convolution              Conv_37                  1 1 536 732 0=128 1=3 4=1 5=1 6=147456
BinaryOp                 Add_38                   2 1 732 531_splitncnn_0 539
Split                    splitncnn_7              1 2 539 539_splitncnn_0 539_splitncnn_1
BatchNorm                BatchNormalization_39    1 1 539_splitncnn_1 540 0=128
Convolution              Conv_40                  1 1 540 735 0=256 1=3 4=1 5=1 6=294912
PReLU                    PRelu_41                 1 1 735 544 0=256
Convolution              Conv_42                  1 1 544 738 0=256 1=3 3=2 4=1 5=1 6=589824
Convolution              Conv_43                  1 1 539_splitncnn_0 741 0=256 1=1 3=2 5=1 6=32768
BinaryOp                 Add_44                   2 1 738 741 549
Split                    splitncnn_8              1 2 549 549_splitncnn_0 549_splitncnn_1
BatchNorm                BatchNormalization_45    1 1 549_splitncnn_1 550 0=256
Convolution              Conv_46                  1 1 550 744 0=256 1=3 4=1 5=1 6=589824
PReLU                    PRelu_47                 1 1 744 554 0=256
Convolution              Conv_48                  1 1 554 747 0=256 1=3 4=1 5=1 6=589824
BinaryOp                 Add_49                   2 1 747 549_splitncnn_0 557
Split                    splitncnn_9              1 2 557 557_splitncnn_0 557_splitncnn_1
BatchNorm                BatchNormalization_50    1 1 557_splitncnn_1 558 0=256
Convolution              Conv_51                  1 1 558 750 0=256 1=3 4=1 5=1 6=589824
PReLU                    PRelu_52                 1 1 750 562 0=256
Convolution              Conv_53                  1 1 562 753 0=256 1=3 4=1 5=1 6=589824
BinaryOp                 Add_54                   2 1 753 557_splitncnn_0 565
Split                    splitncnn_10             1 2 565 565_splitncnn_0 565_splitncnn_1
BatchNorm                BatchNormalization_55    1 1 565_splitncnn_1 566 0=256
Convolution              Conv_56                  1 1 566 756 0=256 1=3 4=1 5=1 6=589824
PReLU                    PRelu_57                 1 1 756 570 0=256
Convolution              Conv_58                  1 1 570 759 0=256 1=3 4=1 5=1 6=589824
BinaryOp                 Add_59                   2 1 759 565_splitncnn_0 573
Split                    splitncnn_11             1 2 573 573_splitncnn_0 573_splitncnn_1
BatchNorm                BatchNormalization_60    1 1 573_splitncnn_1 574 0=256
Convolution              Conv_61                  1 1 574 762 0=256 1=3 4=1 5=1 6=589824
PReLU                    PRelu_62                 1 1 762 578 0=256
Convolution              Conv_63                  1 1 578 765 0=256 1=3 4=1 5=1 6=589824
BinaryOp                 Add_64                   2 1 765 573_splitncnn_0 581
Split                    splitncnn_12             1 2 581 581_splitncnn_0 581_splitncnn_1
BatchNorm                BatchNormalization_65    1 1 581_splitncnn_1 582 0=256
Convolution              Conv_66                  1 1 582 768 0=256 1=3 4=1 5=1 6=589824
PReLU                    PRelu_67                 1 1 768 586 0=256
Convolution              Conv_68                  1 1 586 771 0=256 1=3 4=1 5=1 6=589824
BinaryOp                 Add_69                   2 1 771 581_splitncnn_0 589
Split                    splitncnn_13             1 2 589 589_splitncnn_0 589_splitncnn_1
BatchNorm                BatchNormalization_70    1 1 589_splitncnn_1 590 0=256
Convolution              Conv_71                  1 1 590 774 0=256 1=3 4=1 5=1 6=589824
PReLU                    PRelu_72                 1 1 774 594 0=256
Convolution              Conv_73                  1 1 594 777 0=256 1=3 4=1 5=1 6=589824
BinaryOp                 Add_74                   2 1 777 589_splitncnn_0 597
Split                    splitncnn_14             1 2 597 597_splitncnn_0 597_splitncnn_1
BatchNorm                BatchNormalization_75    1 1 597_splitncnn_1 598 0=256
Convolution              Conv_76                  1 1 598 780 0=256 1=3 4=1 5=1 6=589824
PReLU                    PRelu_77                 1 1 780 602 0=256
Convolution              Conv_78                  1 1 602 783 0=256 1=3 4=1 5=1 6=589824
BinaryOp                 Add_79                   2 1 783 597_splitncnn_0 605
Split                    splitncnn_15             1 2 605 605_splitncnn_0 605_splitncnn_1
BatchNorm                BatchNormalization_80    1 1 605_splitncnn_1 606 0=256
Convolution              Conv_81                  1 1 606 786 0=256 1=3 4=1 5=1 6=589824
PReLU                    PRelu_82                 1 1 786 610 0=256
Convolution              Conv_83                  1 1 610 789 0=256 1=3 4=1 5=1 6=589824
BinaryOp                 Add_84                   2 1 789 605_splitncnn_0 613
Split                    splitncnn_16             1 2 613 613_splitncnn_0 613_splitncnn_1
BatchNorm                BatchNormalization_85    1 1 613_splitncnn_1 614 0=256
Convolution              Conv_86                  1 1 614 792 0=256 1=3 4=1 5=1 6=589824
PReLU                    PRelu_87                 1 1 792 618 0=256
Convolution              Conv_88                  1 1 618 795 0=256 1=3 4=1 5=1 6=589824
BinaryOp                 Add_89                   2 1 795 613_splitncnn_0 621
Split                    splitncnn_17             1 2 621 621_splitncnn_0 621_splitncnn_1
BatchNorm                BatchNormalization_90    1 1 621_splitncnn_1 622 0=256
Convolution              Conv_91                  1 1 622 798 0=256 1=3 4=1 5=1 6=589824
PReLU                    PRelu_92                 1 1 798 626 0=256
Convolution              Conv_93                  1 1 626 801 0=256 1=3 4=1 5=1 6=589824
BinaryOp                 Add_94                   2 1 801 621_splitncnn_0 629
Split                    splitncnn_18             1 2 629 629_splitncnn_0 629_splitncnn_1
BatchNorm                BatchNormalization_95    1 1 629_splitncnn_1 630 0=256
Convolution              Conv_96                  1 1 630 804 0=256 1=3 4=1 5=1 6=589824
PReLU                    PRelu_97                 1 1 804 634 0=256
Convolution              Conv_98                  1 1 634 807 0=256 1=3 4=1 5=1 6=589824
BinaryOp                 Add_99                   2 1 807 629_splitncnn_0 637
Split                    splitncnn_19             1 2 637 637_splitncnn_0 637_splitncnn_1
BatchNorm                BatchNormalization_100   1 1 637_splitncnn_1 638 0=256
Convolution              Conv_101                 1 1 638 810 0=256 1=3 4=1 5=1 6=589824
PReLU                    PRelu_102                1 1 810 642 0=256
Convolution              Conv_103                 1 1 642 813 0=256 1=3 4=1 5=1 6=589824
BinaryOp                 Add_104                  2 1 813 637_splitncnn_0 645
Split                    splitncnn_20             1 2 645 645_splitncnn_0 645_splitncnn_1
BatchNorm                BatchNormalization_105   1 1 645_splitncnn_1 646 0=256
Convolution              Conv_106                 1 1 646 816 0=256 1=3 4=1 5=1 6=589824
PReLU                    PRelu_107                1 1 816 650 0=256
Convolution              Conv_108                 1 1 650 819 0=256 1=3 4=1 5=1 6=589824
BinaryOp                 Add_109                  2 1 819 645_splitncnn_0 653
Split                    splitncnn_21             1 2 653 653_splitncnn_0 653_splitncnn_1
BatchNorm                BatchNormalization_110   1 1 653_splitncnn_1 654 0=256
Convolution              Conv_111                 1 1 654 822 0=512 1=3 4=1 5=1 6=1179648
PReLU                    PRelu_112                1 1 822 658 0=512
Convolution              Conv_113                 1 1 658 825 0=512 1=3 3=2 4=1 5=1 6=2359296
Convolution              Conv_114                 1 1 653_splitncnn_0 828 0=512 1=1 3=2 5=1 6=131072
BinaryOp                 Add_115                  2 1 825 828 663
Split                    splitncnn_22             1 2 663 663_splitncnn_0 663_splitncnn_1
BatchNorm                BatchNormalization_116   1 1 663_splitncnn_1 664 0=512
Convolution              Conv_117                 1 1 664 831 0=512 1=3 4=1 5=1 6=2359296
PReLU                    PRelu_118                1 1 831 668 0=512
Convolution              Conv_119                 1 1 668 834 0=512 1=3 4=1 5=1 6=2359296
BinaryOp                 Add_120                  2 1 834 663_splitncnn_0 671
Split                    splitncnn_23             1 2 671 671_splitncnn_0 671_splitncnn_1
BatchNorm                BatchNormalization_121   1 1 671_splitncnn_1 672 0=512
Convolution              Conv_122                 1 1 672 837 0=512 1=3 4=1 5=1 6=2359296
PReLU                    PRelu_123                1 1 837 676 0=512
Convolution              Conv_124                 1 1 676 840 0=512 1=3 4=1 5=1 6=2359296
BinaryOp                 Add_125                  2 1 840 671_splitncnn_0 679
BatchNorm                BatchNormalization_126   1 1 679 680 0=512
Flatten                  Flatten_127              1 1 680 681
InnerProduct             output                   1 1 681 output 0=512 1=1 2=12845056

Sincerely yours.

**Comment by MirrorYuChen** [comment]
can you provide the model? You only need to change the model name in the project.
