### ISSUE TITLE
Do you use quantize model when you convert to ncnn format ?

### ISSUE THREAD

**Issue by defi0x1** [MirrorYuChen/ncnn_example#55]

**Comment by MirrorYuChen** [comment]
you can quantize model by yourself, I think all will works well.

**Comment by defi0x1** [comment]
@MirrorYu mi
 But, In your model you provided, do you apply any quantize process ?

**Comment by MirrorYuChen** [comment]
please refer to ncnn wiki: 
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
