### ISSUE TITLE
人脸对齐关键点有问题？

### ISSUE THREAD

**Issue by wjgarnett** [MirrorYuChen/ncnn_example#57]
感谢作者开源ncnn_example工程，我从中获益良多。我在调试时发现一个可能的bug,人脸关键点对齐选取的关键点似乎有些问题。下图是我可视化出来选取的五个关键点。

**Comment by wjgarnett** [comment]
![image](https://user-images.githubusercontent.com/9332073/174218066-fcf75bd1-9b7e-4e4d-b7fc-758dc9b93e7c.png)
个人认为，相似变换里设置的参考点对应的关键点应该是眼睛中心+鼻尖+嘴角

**Comment by MirrorYuChen** [comment]
<img width="582" alt="image" src="https://user-images.githubusercontent.com/49817428/174429402-8010274f-8a29-4fc0-aa19-5e20ac5ec022.png">

**Comment by MirrorYuChen** [comment]
你对一下点序，应该没错才对

**Comment by MirrorYuChen** [comment]
<img width="473" alt="image" src="https://user-images.githubusercontent.com/49817428/174429443-7c152016-b08f-4c74-89fa-31f2651d5667.png">

**Comment by MirrorYuChen** [comment]
长时间没有回复，默认解决了~

**Comment by wjgarnett** [comment]
![image](https://user-images.githubusercontent.com/9332073/177303530-d4ec9612-a787-4693-a9d7-37b62b630a92.png)

**Comment by wjgarnett** [comment]
我在你代码里加了这几行可视化代码，可视化出来的结果确实有我提到的问题，麻烦再确认下呢。我这里可视化出来keypoints中的顺序和你给的示意图中的顺序不一致。

**Comment by MirrorYuChen** [comment]
测试代码及测试图片提供一下，我这边确认一下

**Comment by wjgarnett** [comment]
代码直接clone你的工程，只是添加了红框那几行代码，图片用的你提供的默认图片：https://github.com/MirrorYuChen/ncnn_example/blob/master/data/images/4.jpg

**Comment by MirrorYuChen** [comment]
最近比较忙哈，这周周末我对一下

**Comment by wjgarnett** [comment]
没事，不急哈。

**Comment by MirrorYuChen** [comment]
你是对的，我这边ZQLandmark的点序是上面那种，后面新加的insightface的点序不同这个还没有适配，这个你需要自己调整一下，测试ZQLandmark可以按照如下方式修改：
<img width="760" alt="image" src="https://user-images.githubusercontent.com/49817428/179240570-033c6233-fd66-4fcb-a3f2-bb56f4b9d922.png">

**Comment by MirrorYuChen** [comment]
如果要用insightface的点序，你按照这边的取点的位置，自己取一下点适配一下哈。

**Comment by wjgarnett** [comment]
好的，谢谢！
