### ISSUE TITLE
有关人脸识别模型的问题

### ISSUE THREAD

**Issue by leizhu1989** [MirrorYuChen/ncnn_example#61]
大佬，请问下，人脸识别的模型支持戴口罩的人脸吗

**Comment by MirrorYuChen** [comment]
这个之前没找到开源的，还不支持。

**Comment by leizhu1989** [comment]
@MirrorYuChen 谢谢大佬回复，还有个人脸识别相关的问题想请教下啊。我发现目前人脸检测、特征点的基本还比较准。人脸对齐的和识别的像是瓶颈，我用了大佬的代码跑了下，我稍微改动下对齐的方法就识别不出来了。请问下这个识别的模型是要和对齐的方法严格匹配吗。也就是说我用仿射变换的方法对齐图像，那么训练的时候是不是也要使用这种对齐的方法预处理数据之后再训练识别模型呢，求大佬指教

**Comment by MirrorYuChen** [comment]
对齐目标点是根据训练人脸识别模型尺寸来做对齐的，具体你可以看一下insightface项目。你说的修改对齐方法，我没有很看懂是什么意思

**Comment by leizhu1989** [comment]
@MirrorYuChen 嗯嗯，我改了下代码，就正常了，谢谢大佬。还有个问题啊，大佬请问，转换成的ncnn模型原始的pytorch模型可以开源吗
