### ISSUE TITLE
有关mask戴口罩检测模型

### ISSUE THREAD

**Issue by leizhu1989** [MirrorYuChen/ncnn_example#62]
大佬请问下，戴口罩检测的模型是通过哪个项目和哪些数据集训练的呢，原始的pytorch模型可以发一份吗

**Comment by MirrorYuChen** [comment]
https://github.com/deepinsight/insightface/tree/master/detection/retinaface_anticov

**Comment by MirrorYuChen** [comment]
应该是个mxnet的模型
