### ISSUE TITLE
关于左博士106点模型的转换

### ISSUE THREAD

**Issue by nidetaoge** [MirrorYuChen/ncnn_example#9]
你好，感谢你关于这个项目的为大家开源的工作！看到主页上说对原始左博士的mxnet106点模型的修改是在json里，删去不支持的层，如下：
https://github.com/zuoqing1988/ZQCNN/issues/50
我只删除了 "name": "landmark_target", "name": "landmark_pred","name": "negative_mining",但是还是mxnet加载不成功，麻烦能否给我提供一下你修改好的mxnet的json文件呢？谢谢！

**Comment by MirrorYuChen** [comment]
直接转换，转换完了修改一下param文件就行了，不用改json文件，我对mxnet不熟，不敢乱改~

**Comment by MirrorYuChen** [comment]
我在readme文档中已经给了对应修改的参考链接~
